--- 
apiVersion: v1
kind: Deployment
metadata: 
  labels: 
    app: web
  name: EmpWeb
spec: 
  containers: 
    - 
      image: NodeJS
      name: front-end
      ports: 
        - 
          containerPort: 8888
    - 
      image: mongo
      name: db
      ports: 
        - 
          containerPort: 27017
    - 
      image: devopsedu/employee
      name: emp-add
      ports: 
        - 
          containerPort: 80
